1: 
	gcc task1.c -o fork.exe && ./fork.exe

2: 
	gcc task2.c -o wait.exe && ./wait.exe 

3: 
	gcc task3.c -o exec.exe && ./exec.exe

4: 
	gcc task3.c -o pipe.exe  && ./pipe.exe

5: 
	gcc task3.c -o pipe.exe && ./pipe.exe


clean:
	rm *.o *.exe