FLAGS = -Wall -o


1: 
	gcc task1.c $(FLAGS) fork.exe && ./fork.exe

2: 
	gcc task2.c $(FLAGS) wait.exe && ./wait.exe 

3: 
	gcc task3.c $(FLAGS) exec.exe && ./exec.exe

4: 
	gcc task4.c $(FLAGS) pipe.exe  && ./pipe.exe

5: 
	gcc task5.c $(FLAGS) pipe.exe && ./pipe.exe


clean:
	rm *.exe